version: "3"

services:
  opendata-voter:
    image: dk-reg.10ninox.com/ds-dga/opendata-vote:latest
    expose:
      - 80
    networks:
      - proxy_default
    environment:
      - REACT_APP_GA_TRACKING_ID=G-TXX6D46J3V
      - NODE_ENV=production

networks:
  proxy_default:
    external: true
